project:
  type: website
  output-dir: docs

website:
  title: "Jinheng Cen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3  
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
          - href: weekly-notes/week-05-notes.qmd
            text: Week 5
          - href: weekly-notes/week-06-notes.qmd
            text: Week 6 
          - href: weekly-notes/week-07-notes.qmd
            text: Week 7  
          - href: weekly-notes/week-09-notes.qmd
            text: Week 9 
          - href: weekly-notes/week-10-notes.qmd
            text: Week 10
          - href: weekly-notes/week-11-notes.qmd
            text: Week 11
      - text: Labs
        menu:
          - href: labs/lab_0.qmd
            text: lab 0
      - text: Assignments
        menu:
          - href: assignments/assignment_1/assignment_1.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: assignments/assignment_2/Cen_Jinheng_Assignment2.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: assignments/assignment_4/Cen_Jinheng_Assignment4.qmd
            text: "Assignment 4: Predictive Policing"
          - href: assignments/assignment_5/Cen_Yang_Assignment5.Rmd
            text: "Assignment 5: Shared Bike Prediction"
      - text: Midterm
        menu: 
          - href: midterm/appendix/Midterm_2025.qmd
            text: "Appendix: Philadelphia Housing Price Prediction"
          - href: midterm/slides/Midterm_slides_v3.qmd
            text: "Slide: Philadelphia Housing Price Prediction"
            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto